---
language: python
python: "2.7"

services:
  - docker

before_install:
  - docker pull oharsta/repository:ubuntu_unminimize
  - docker run --name ubuntu_container  -td oharsta/repository:ubuntu_unminimize

install:
  - pip install ansible

script:
  - ansible-playbook -i inventory.yml playbook.yml
