---
language: python
python: "2.7"

services:
  - docker

before_install:
  - docker pull oharsta/repository:ubuntu_unminimize
  - docker run --name ubuntu_container  -td oharsta/repository:ubuntu_unminimize

install:
  - pip install ansible

script:
  - ansible-playbook -i inventory.yml playbook.yml --syntax-check
  - ansible-playbook -i inventory.yml playbook.yml
  - ansible-playbook -i inventory.yml playbook.yml | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
