---
- name: Update cache
  apt:
    update_cache: yes

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apache2
      - apache2-utils
      - ssl-cert
      - libapache2-mod-wsgi-py3
      - python3-pip

- name: enabled mod_proxy
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2

- name: enabled wsgi
  apache2_module: name=wsgi state=present
  notify:
    - restart apache2

- name: Start apache2
  service: name=apache2 state=started
