---
- name: Update cache
  apt:
    update_cache: yes

- name: Install GPG
  apt:
    name: gpg

- name: import MongoDB public GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4

- name: Add MongoDB repository into sources list
  apt_repository:
    repo: deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse
    state: present

- name: Install MongoDB package
  apt:
    name: mongodb

- name: Start MongoDB
  service: name=mongodb state=started

- name: Check if mongo is installed. If not, the admin user is created
  stat:
    path: "/var/lib/mongodb"
  register: mongo_present

- name: Install pymongo
  pip:
    name: pymongo
    executable: "/usr/bin/pip3"

- name: Add the admin user
  mongodb_user:
    database: admin
    name: admin
    password: "{{ mongo_passwords.admin }}"
    login_port: 27017
    roles: userAdminAnyDatabase
    state: present
  when:
    - mongo_present.stat.exists == False

- name: Create mongo database users
  mongodb_user:
    login_database: admin
    login_user: admin
    login_password: "{{ mongo_passwords.admin }}"
    database: "{{ item[0].db_name }}{{ item[1] }}"
    name: "{{ item[0].name }}"
    password: "{{ item[0].password }}"
    roles: "{{ item[0].roles }}"
  with_nested:
    - "{{ mongo_users }}"
    - ['', '_test']

- name: Install mongodb.conf file with authorisation enabled
  template:
    src: "mongodb.conf.j2"
    dest: "/etc/mongodb.conf"
  register: mongo_conf_changed

- name: Restart Mongo
  service: name=mongodb state=restarted
  when:
    - mongo_conf_changed.changed

