---
- hosts: local
  gather_facts: yes
  become: true

  pre_tasks:
    - name: Read vars from secrets file
      include_vars: "{{ secrets_file }}"
      tags:
        - always

  roles:
    - { role: apache2,      tags: ['apache2' ] }
    - { role: mongodb,      tags: ['mongodb' ] }
